"use client";
import {useState} from "react";
import {ArrowRight,Check,ChevronDown,FileSearch,Globe,Lock,Menu,MessageSquareText,ShieldCheck,Sparkles,X} from "lucide-react";
import type {Analysis,CheckType} from "@/lib/analyzer";
const modes:[CheckType,string,string][]=[["url","Check a website","URL"],["message","Check a message","SMS · Email · DM"],["claim","Check a claim","Evidence review"]];
export default function Home(){
 const [mode,setMode]=useState<CheckType>("url"),[input,setInput]=useState(""),[result,setResult]=useState<Analysis|null>(null),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(false);
 async function run(){setBusy(true);setResult(null);try{const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:mode,input})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d.analysis)}catch(e){setResult({type:mode,subject:"No result",score:0,confidence:100,risk:"unknown",headline:"Analysis could not run",summary:e instanceof Error?e.message:"Please try again.",signals:[],recommendation:"Check the input and try again.",limitations:["No result was generated."]})}finally{setBusy(false)}}
 return <main>
 <nav className="nav shell"><a className="brand" href="#"><span className="brandmark">V</span>veriq</a><div className={"navlinks "+(mobile?"open":"")}><a href="#how">How it works</a><a href="#checks">Checks</a><a href="#privacy">Privacy</a></div><button className="iconbtn mobilemenu" onClick={()=>setMobile(!mobile)} aria-label="Toggle navigation">{mobile?<X/>:<Menu/>}</button><a className="navcta" href="#checker">Check something <ArrowRight size={16}/></a></nav>
 <section className="hero shell"><div className="eyebrow"><span className="pulse"></span> Digital trust intelligence</div><h1>Before you <em>trust it</em>, check it.</h1><p className="hero-copy">Analyze websites, messages and claims using multiple signals, transparent reasoning and clear next steps.</p><div className="hero-actions"><a className="button primary" href="#checker">Check something <ArrowRight size={17}/></a><a className="button ghost" href="#how">See how it works</a></div><div className="trust-note"><ShieldCheck size={17}/> No fake certainty. Every result shows evidence, confidence and limitations.</div></section>
 <section id="checker" className="checker-wrap shell"><div className="checker"><div className="checker-top"><div><span className="kicker">QUICK CHECK</span><h2>What do you want to verify?</h2></div><span className="privacy-chip"><Lock size={13}/> Privacy-first</span></div><div className="mode-grid">{modes.map(([id,title,sub])=><button key={id} className={"mode "+(mode===id?"selected":"")} onClick={()=>{setMode(id);setResult(null)}}>{id==="url"?<Globe/>:id==="message"?<MessageSquareText/>:<FileSearch/>}<span><strong>{title}</strong><small>{sub}</small></span>{mode===id&&<Check className="mode-check" size={17}/>}</button>)}</div><div className="input-row">{mode==="url"?<input value={input} onChange={e=>setInput(e.target.value)} placeholder="https://example.com" onKeyDown={e=>e.key==="Enter"&&run()}/>:<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==="message"?"Paste the message, SMS or email you received…":"Paste a claim you want to investigate…"} rows={4}/>}<button className="button primary analyze" disabled={busy||!input.trim()} onClick={run}>{busy?"Analyzing…":"Analyze"} <ArrowRight size={17}/></button></div>{busy&&<div className="stages"><span>✓ Identifying input</span><span>✓ Collecting signals</span><span className="active">⏳ Evaluating trust</span><span>○ Building report</span></div>}{result&&<ResultCard result={result}/>}</div></section>
 <section id="checks" className="section shell"><div className="section-head"><span className="kicker">ONE TRUST LAYER</span><h2>Different questions. Different evidence.</h2><p>Veriq does not collapse authenticity, credibility and security into one magic detector.</p></div><div className="feature-grid"><Feature icon={<Globe/>} title="Website trust" text="Inspect URL-level risk signals without confusing HTTPS with legitimacy."/><Feature icon={<MessageSquareText/>} title="Scam screening" text="Surface urgency, impersonation, payment and secret-request patterns."/><Feature icon={<FileSearch/>} title="Claim review" text="Separate what a statement says from what its available evidence establishes."/><Feature icon={<Sparkles/>} title="Explainable results" text="See the signal, confidence, limitation and recommended next step."/></div></section>
 <section id="how" className="section how"><div className="shell how-grid"><div><span className="kicker">HOW IT WORKS</span><h2>Trust is a chain of evidence.</h2><p>Each analysis is designed as a modular pipeline so future provenance, threat intelligence, media forensics and source intelligence can plug in without rebuilding the product.</p></div><div className="steps"><Step n="01" t="Classify" d="Identify what kind of thing you are checking."/><Step n="02" t="Collect signals" d="Gather only signals that can actually be supported."/><Step n="03" t="Explain" d="Separate result confidence from evidence strength."/><Step n="04" t="Recommend" d="Turn uncertainty into a safer next action."/></div></div></section>
 <section id="privacy" className="privacy section shell"><Lock/><div><span className="kicker">BUILT FOR TRUST</span><h2>Your data should not become the product.</h2><p>The MVP keeps analysis logic server-side and does not claim to retain or train on private uploads. Future storage will use explicit retention controls, access policies and deletion workflows.</p></div></section>
 <footer className="footer shell"><a className="brand" href="#"><span className="brandmark">V</span>veriq</a><span>Digital trust, explained.</span><span>© 2026 Veriq</span></footer></main>
}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Step({n,t,d}:{n:string;t:string;d:string}){return <div className="step"><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>}
function ResultCard({result}:{result:Analysis}){return <div className="result"><div className="result-main"><div><span className={"risk "+result.risk}>{result.risk.toUpperCase()}</span><h3>{result.headline}</h3><p>{result.summary}</p></div><div className="score"><strong>{result.score}</strong><span>/100</span><small>trust</small></div></div><div className="result-meta"><span>Confidence <b>{result.confidence}%</b></span><span>Evidence strength <b>{result.signals.length?"Mixed":"Insufficient"}</b></span></div><div className="signals">{result.signals.map((s,i)=><div className="signal" key={i}><i className={s.kind}></i><div><strong>{s.label}</strong><p>{s.detail}</p></div><span>{s.confidence}%</span></div>)}</div><div className="recommend"><b>What to do</b><p>{result.recommendation}</p></div><details><summary>Limitations & methodology <ChevronDown size={16}/></summary><ul>{result.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul></details></div>}