"use client";
import {useState} from "react";
import {ArrowRight,Check,FileSearch,Globe,Lock,MessageSquareText,Sparkles} from "lucide-react";
import Shell from "../components/Shell";
import ReportCard from "../components/ReportCard";
import {saveReport,type StoredReport} from "../lib/report-store";
import type {Analysis,CheckType} from "../lib/analyzer";

const modes:[CheckType,string,string][]=[["url","Check a website","URL"],["message","Check a message","SMS · Email · DM"],["claim","Check a claim","Evidence review"]];

export default function Home(){
 const [mode,setMode]=useState<CheckType>("url"),[input,setInput]=useState(""),[result,setResult]=useState<Analysis|null>(null),[saved,setSaved]=useState<StoredReport|null>(null),[busy,setBusy]=useState(false);
 function validate(){const v=input.trim();if(!v)return "Enter something to analyze.";if(mode==="url"){try{const u=new URL(v.startsWith("http")?v:"https://"+v);if(!u.hostname.includes("."))return "Enter a website address such as example.com.";return ""}catch{return "Enter a valid website address such as https://example.com."}}return ""}
 async function run(){const error=validate();if(error){setResult({type:mode,subject:"Input needs review",score:0,confidence:100,risk:"unknown",headline:"Check the input type",summary:error,signals:[],recommendation:"Choose the matching check type and try again.",limitations:["No trust score was generated because the input was not analyzed."]});return}setBusy(true);setResult(null);setSaved(null);try{const response=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:mode,input})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Analysis failed.");const analysis=data.analysis as Analysis;setResult(analysis);try{setSaved(saveReport(analysis))}catch{}}catch(e){setResult({type:mode,subject:"No result",score:0,confidence:100,risk:"unknown",headline:"Analysis could not run",summary:e instanceof Error?e.message:"Please try again.",signals:[],recommendation:"Please try again.",limitations:["No result was generated."]})}finally{setBusy(false)}}
 return <Shell><main>
 <section className="hero shell"><div className="eyebrow"><span className="pulse"/> Digital trust intelligence</div><h1>Before you <em>trust it</em>, check it.</h1><p className="hero-copy">Analyze websites, messages and claims using observable signals, transparent reasoning and clear next steps.</p><div className="hero-actions"><a className="button primary" href="#checker">Check something <ArrowRight size={17}/></a><a className="button ghost" href="/how-it-works">See how it works</a></div><div className="trust-note"><Lock size={15}/> No fake certainty. Results expose evidence, confidence and limitations.</div></section>
 <section id="checker" className="checker-wrap shell"><div className="checker"><div className="checker-top"><div><span className="kicker">QUICK CHECK</span><h2>What do you want to verify?</h2></div><span className="privacy-chip"><Lock size={13}/> Privacy-first</span></div><div className="mode-grid">{modes.map(([id,title,sub])=><button key={id} className={"mode "+(mode===id?"selected":"")} onClick={()=>{setMode(id);setResult(null)}}>{id==="url"?<Globe/>:id==="message"?<MessageSquareText/>:<FileSearch/>}<span><strong>{title}</strong><small>{sub}</small></span>{mode===id&&<Check className="mode-check" size={17}/>}</button>)}</div><div className="input-row">{mode==="url"?<input value={input} onChange={e=>setInput(e.target.value)} placeholder="https://example.com" onKeyDown={e=>e.key==="Enter"&&run()}/>:<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==="message"?"Paste the message, SMS or email you received…":"Paste a claim you want to investigate…"} rows={4}/>}<button className="button primary analyze" disabled={busy||!input.trim()} onClick={run}>{busy?"Analyzing…":"Analyze"} <ArrowRight size={17}/></button></div>{busy&&<div className="stages"><span>✓ Identifying input</span><span>✓ Collecting live signals</span><span className="active">⏳ Evaluating trust</span><span>○ Building report</span></div>}{result&&<><ReportCard result={result}/>{saved&&<p className="saved-note">Saved to this browser · <a href={"/report/"+saved.id}>Open report →</a></p>}</>}</div></section>
 <section id="checks" className="section shell"><div className="section-head"><span className="kicker">ONE TRUST LAYER</span><h2>Different questions. Different evidence.</h2><p>Authenticity, credibility, claim evidence and security are related—but they are not the same question.</p></div><div className="feature-grid"><Feature icon={<Globe/>} title="Website trust" text="Inspect live URL-level signals without confusing HTTPS with legitimacy."/><Feature icon={<MessageSquareText/>} title="Scam screening" text="Surface urgency, impersonation, payment and secret-request patterns."/><Feature icon={<FileSearch/>} title="Claim review" text="Separate what a statement says from what its available evidence establishes."/><Feature icon={<Sparkles/>} title="Explainable results" text="See the signal, confidence, limitation and recommended next step."/></div></section>
 <section className="section how"><div className="shell how-grid"><div><span className="kicker">HOW IT WORKS</span><h2>Trust is a chain of evidence.</h2><p>Veriq uses a modular analysis pipeline so future provenance, threat intelligence, media forensics and source intelligence can plug in without rebuilding the product.</p></div><div className="steps">{[["01","Classify","Identify what kind of thing you are checking."],["02","Collect signals","Gather signals that can actually be supported."],["03","Explain","Separate result confidence from evidence strength."],["04","Recommend","Turn uncertainty into a safer next action."]].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div></div></section>
 </main></Shell>
}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}